name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: write # for pre-commit-action
    steps:
      - name: Check out repository.
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
      - name: Use Docker in rootless mode.
        uses: ./
      - name: Run pre-commit hooks.
        uses: ScribeMD/pre-commit-action@33bd9c94e22d6b9532fcd80a5ba36780ea311309 # 0.9.23
      - name: Send Slack notification with job status.
        if: always()
        uses: ScribeMD/slack-templates@c7982d3a4caac776a8faafff78462927293175ef # 0.6.12
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
